#!/usr/bin/env bash
# a script that transfers a file from client to a server
# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP  USERNAME PATH_TO_SSH_KEY"
	exit
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# transfer file with scp
scp -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~
