#!/usr/bin/env bash
# a bash script to install nginx in the server
sudo apt-get install -y nginx && sudo sed -i 's/.*/Hello World!                    /' /var/www/html/*.html && sudo service nginx restart
