#!/usr/bin/env bash
# install nginx and set it up to listen on port 80 and its default page should contain the string "Hello World!"
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i '/listen \[::\]:80 default_server;/a \    location \/redirect_me { return 301 https:\/\/www.youtube.com\/; }' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
