#!/usr/bin/env bash
# install and configure HAProxy on lb-01 server
sudo apt-get update
sudo apt-get install haproxy -y

# configure HAProxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend appservers

backend appservers
    mode http
    balance roundrobini
    server web-01 54.84.162.208:80 check
    server web-02 54.175.225.209:80 check
EOF

# enable HAProxy init script
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# restart HAProxy to apply changes
sudo service haproxy restart
