#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it
# Usage: ./5-mysql_backup password
mysqldump -uroot -p "$1" --all-databases > backup.sql 
tar -czvf "$(date +%H%M%S).tar.gz" backup.sql
