#!/usr/bin/env bash
# this script save its PID in a file, display "To infinity and beyond" indefinitely, display "I hate the kill command" when receiving a SIGTERM signal and "Y U no love me?!" when receiving a SIGINT signal.
# Lastly, it deletes the PID file and exit when receiving a SIGQUIT or SIGTERM signal.

# save PID in a file
echo $$ > /tmp/my_process.pid
# handle signals
trap "rm -f /tmp/my_process.pid && echo 'I hate the kill command' && exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /tmp/my_process.pid && echo 'Y U no love me?!' && exit" SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
