#!/usr/bin/env bash
# reads the content of the file /etc/passwd and prints the username, user id, and home directory of each user
while IFS=: read -r f1 _ f3 _ _ f6 _
do
    printf "%s:%s:%s\n" "$f1" "$f3" "$f6"
done < /etc/passwd
