#!/usr/bin/env bash
# display the content of the file /etc/passwd using the while loop and IFS such that:
# "the user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the PASSWORD, more info about the user here: USER ID INFO"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by %s, more info about the user here: %s\n" "$f1" "$f4" "$f6" "$f7" "$f3" "$f2" "$f5"
done < /etc/passwd
