#!/usr/bin/env bash
# loop 20 times using while loop and display "bad luck from China" for 4th loop, 
# "bad luck from Japan" for 9th loop, "bad luck from Italy" for 17th loop
i=1
while [ $i -le 20 ]; do 
    case $i in
        4)
            echo "bad luck from Japan"
            ;;
        9)
            echo "bad luck from Italy"
            ;;
        17)
            echo "bad luck from China"
            ;;
        *)
            echo $i
            ;;
    esac
    i=$((i+1))
done
