#!/usr/bin/env bash
# read the content of the file "school" and does the following:
# checks if the file exists and displays "school file exists" if it exists
# otherwise displays "school file does not exist" if it does not exist
# if the file exists, checks if the file is empty and displays "school file is empty" if it is empty
# otherwise, displays "school file is not empty" and
# if the file is a regular file and not a directory, displays "school is a regular file" otherwise nothing
file="school"
if [ -e "$file" ]; then
    echo "$file file exists"
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
    if [ -f "$file" ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
