#!/usr/bin/env bash
# a script that configures an Ubuntu server with the below requirements.
# Requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
# Replace localhost IP address
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new

# Replace facebook.com IP address
facebook_ip=$(nslookup facebook.com | grep -m1 -oP 'Address: \K[\d.]+')
sed -i 's/'"$facebook_ip"'/8.8.8.8/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
